In [1]:
print("test")

test


In [1]:
import torch

/home/superrama/Lab1_pytorch/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:368: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [3]:
print(torch.__version__)

2.14.1+cu130


In [4]:
print(torch.cuda.is_available())

False


In [8]:
x = torch.tensor([2,4,6])
y = torch.tensor([[1,2,3], [3, 4, 5]])
x1 = torch.zeros(6)

In [7]:
print(x.shape, y.shape)

torch.Size([3]) torch.Size([2, 3])


In [9]:
x1

tensor([0., 0., 0., 0., 0., 0.])

In [10]:
print(x.dtype)

torch.int64


In [11]:
y2=y.to(torch.float32)

In [12]:
y2

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [13]:
z = torch.randn(5,6)

In [14]:
z

tensor([[-0.1479,  0.0640,  0.9260, -1.3556, -0.0939,  0.1185],
        [ 0.6002,  0.5742, -1.4110,  0.5901, -0.3945,  0.1257],
        [ 1.6743,  0.0431, -1.0214,  1.1011,  0.9484, -2.7993],
        [-0.4891, -0.2919, -0.1098, -0.4450,  1.7282, -0.9488],
        [ 1.0587, -0.6364,  0.5231,  0.1063, -0.1301,  0.6873]])

In [15]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [16]:
device

device(type='cpu')

In [17]:
z.to(device)

tensor([[-0.1479,  0.0640,  0.9260, -1.3556, -0.0939,  0.1185],
        [ 0.6002,  0.5742, -1.4110,  0.5901, -0.3945,  0.1257],
        [ 1.6743,  0.0431, -1.0214,  1.1011,  0.9484, -2.7993],
        [-0.4891, -0.2919, -0.1098, -0.4450,  1.7282, -0.9488],
        [ 1.0587, -0.6364,  0.5231,  0.1063, -0.1301,  0.6873]])

In [21]:
A = torch.tensor([ [1,2,3], [4,5,6]]).to(device)
B = torch.tensor( [[5,1,6], [9,2,8]]).to(device)

In [22]:
C = A+B

In [23]:
C

tensor([[ 6,  3,  9],
        [13,  7, 14]])