In [1]:
print("test")

test


In [3]:
import torch

/home/superrama/Lab1_pytorch/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:368: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [4]:
print(torch.__version__)

2.14.1+cu130


In [5]:
print(torch.cuda.is_available())

False


In [6]:
x = torch.tensor([2,4,6])
y = torch.tensor([[1,2,3], [3, 4, 5]])
x1 = torch.zeros(6)

In [7]:
print(x.shape, y.shape)

torch.Size([3]) torch.Size([2, 3])


In [8]:
x1

tensor([0., 0., 0., 0., 0., 0.])

In [9]:
print(x.dtype)

torch.int64


In [10]:
y2=y.to(torch.float32)

In [11]:
y2

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [12]:
z = torch.randn(5,6)

In [13]:
z

tensor([[ 1.0713,  1.4271, -0.6378, -0.2962, -0.3072, -0.2560],
        [-0.1734,  0.9208,  1.0590,  0.5440,  0.0523,  0.1157],
        [ 0.7680,  0.3046, -1.5678, -0.8230,  0.8381, -0.5218],
        [-1.2503,  0.9478, -0.4158,  1.3298,  0.1484, -0.4081],
        [ 0.2367, -0.6620,  0.6229,  1.3484, -2.3419, -1.0955]])

In [14]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [15]:
device

device(type='cpu')

In [16]:
z.to(device)

tensor([[ 1.0713,  1.4271, -0.6378, -0.2962, -0.3072, -0.2560],
        [-0.1734,  0.9208,  1.0590,  0.5440,  0.0523,  0.1157],
        [ 0.7680,  0.3046, -1.5678, -0.8230,  0.8381, -0.5218],
        [-1.2503,  0.9478, -0.4158,  1.3298,  0.1484, -0.4081],
        [ 0.2367, -0.6620,  0.6229,  1.3484, -2.3419, -1.0955]])

In [17]:
A = torch.tensor([ [1,2,3], [4,5,6]]).to(device)
B = torch.tensor( [[5,1,6], [9,2,8]]).to(device)

In [18]:
C = A+B

In [19]:
C

tensor([[ 6,  3,  9],
        [13,  7, 14]])

### Calcul de gradient

In [32]:
x = torch.tensor(3.0)
w = torch.tensor(4.0, requires_grad=True)
b = torch.tensor(6.0, requires_grad=True)

y = w * x + b
loss = (y -10) **2

In [27]:
loss

tensor(64., grad_fn=<PowBackward0>)

In [28]:
loss.backward()

In [29]:
print(w.grad.item())

48.0


In [30]:
print(b.grad.item())

16.0


In [31]:
dw, db = torch.autograd.grad(loss, (w, b))

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.